import { getCurrentUser } from "../../../lib/get-current-user";
import { listOrders, listPlans } from "../../../api/lib/data-store";
import { OrdersList } from "./orders-list";

export default async function OrdersPage() {
  const user = await getCurrentUser();
  const orders = user ? await listOrders(user.id) : [];
  const plans = user ? await listPlans() : [];
  const planMap = new Map(plans.map((plan) => [plan.id, plan]));

  const enrichedOrders = orders.map((order) => ({
    ...order,
    planName: planMap.get(order.planId)?.name ?? "Plan",
  }));

  const totalSpent = orders.reduce((sum, o) => sum + o.total, 0);
  const upcoming = orders
    .filter((o) => o.status !== "delivered")
    .sort((a, b) => (a.deliveryDate < b.deliveryDate ? -1 : 1));
  const nextUpcoming = upcoming[0];

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="text-xs uppercase tracking-[0.26em] text-[#BC8A31]">
          Orders
        </p>
        <h1 className="mt-2 font-display text-3xl text-[#17251C]">
          Order history
        </h1>
        <p className="mt-1 max-w-md text-[15px] text-[#6B6558]">
          Every box generated by your subscription, from checkout through to
          your door.
        </p>
      </div>

      <div className="grid gap-5 sm:grid-cols-3">
        <StatCard label="Total orders" value={String(orders.length)} />
        <StatCard
          label="Total spent"
          value={`₦${totalSpent.toLocaleString()}`}
        />
        <StatCard
          label="Next delivery"
          value={
            nextUpcoming
              ? new Date(nextUpcoming.deliveryDate).toLocaleDateString(
                  "en-NG",
                  {
                    month: "short",
                    day: "numeric",
                  },
                )
              : "All caught up"
          }
        />
      </div>

      <OrdersList orders={enrichedOrders} />
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-3xl border border-[#E4DCC8] bg-white p-5">
      <p className="text-xs uppercase tracking-[0.26em] text-[#6B6558]">
        {label}
      </p>
      <p className="mt-3 text-2xl font-semibold text-[#17251C]">{value}</p>
    </div>
  );
}
